package com.myteam.employeecms;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Employee implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "EMPLOYEE_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "EMPLOYEE_ID_SEQ", name = "EMPLOYEE_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label(value = "lastName")
	private java.lang.String lastName;

	@org.kie.api.definition.type.Label(value = "Email")
	private java.lang.String email;

	@org.kie.api.definition.type.Label(value = "Phone")
	private java.lang.String phone;

	@org.kie.api.definition.type.Label(value = "Address")
	private java.lang.String address;

	@org.kie.api.definition.type.Label(value = "Birthdate")
	private java.util.Date birthDate;

	@org.kie.api.definition.type.Label(value = "Department")
	private java.lang.String department;

	@org.kie.api.definition.type.Label(value = "Location")
	private java.lang.String location;

	@org.kie.api.definition.type.Label(value = "Remote")
	private java.lang.Boolean remote;

	public Employee() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getPhone() {
		return this.phone;
	}

	public void setPhone(java.lang.String phone) {
		this.phone = phone;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.util.Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(java.util.Date birthDate) {
		this.birthDate = birthDate;
	}

	public java.lang.String getDepartment() {
		return this.department;
	}

	public void setDepartment(java.lang.String department) {
		this.department = department;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public java.lang.Boolean getRemote() {
		return this.remote;
	}

	public void setRemote(java.lang.Boolean remote) {
		this.remote = remote;
	}

	public Employee(java.lang.Long id, java.lang.String name,
			java.lang.String lastName, java.lang.String email,
			java.lang.String phone, java.lang.String address,
			java.util.Date birthDate, java.lang.String department,
			java.lang.String location, java.lang.Boolean remote) {
		this.id = id;
		this.name = name;
		this.lastName = lastName;
		this.email = email;
		this.phone = phone;
		this.address = address;
		this.birthDate = birthDate;
		this.department = department;
		this.location = location;
		this.remote = remote;
	}

}